LangaraVoyagers/project-2

README.md
=> chore: workflow demo

index.html, package.json, src/index.css, src/layouts/BasicHome.tsx, src/layouts/MainLayout.tsx, src/main.tsx, src/pages/app/App.tsx, src/pages/pickers/Pickers.tsx, src/pages/pickers/index.tsx, src/shared/paths.ts, src/theme.tsx, yarn.lock
Ticket:
https://team-voyagers.atlassian.net/browse/P2-180?atlOrigin=eyJpIjoiNGM2YjYzYjg4MDU5NDBmNzk3M2NhNWE0NDA3ZmY5YzkiLCJwIjoiaiJ9
=> feat: add material ui package and provider

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
Added a custom issue form for bug reporting. 
When a user wants to add a bug report, they will be able to select the custom form:
This is what the form will look like:
=> P2 158 issue tracking system screen recording

.env, .env.example, .gitignore, package-lock.json, package.json, src/api/axios.ts, src/api/pickers.ts, src/components/pickers/PickerDrawer.tsx, src/pages/Pickers/Pickers.tsx, vite.config.ts, yarn.lock
Ticket:
https://team-voyagers.atlassian.net/browse/P2-167?atlOrigin=eyJpIjoiMGZhNTlkOGEzMDk4NDRiZmE2NTc4MWExN2YyNzIzNTIiLCJwIjoiaiJ9
=> feat: create picker, add mutation to PickerDrawer and update query cache

README.md, package-lock.json, package.json, src/layouts/MainLayout.tsx, src/pages/Pickers/Pickers.tsx, yarn.lock
https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?assignee=712020%3Aa4d78f0d-920a-427a-a5ce-b36979797950&selectedIssue=P2-181
=> P2 181 fe icons

src/api/pickers.ts, src/components/pickers/CreatePicker.tsx, src/components/pickers/PickerDrawer.tsx, src/components/pickers/UpdatePicker.tsx, src/context/AlertProvider.tsx, src/layouts/MainLayout.tsx, src/pages/App/App.tsx, src/pages/Pickers/Pickers.tsx, src/shared/paths.ts
Ticket:
https://team-voyagers.atlassian.net/browse/P2-168?atlOrigin=eyJpIjoiOTA3ZDA3NzgyMDk3NGExN2I3ODhhN2E2NmRjNjYzNTciLCJwIjoiaiJ9
=> P2 168 fe edit picker

src/api/pickers.ts, src/components/pickers/PickerDrawer.tsx
Ticket:
https://team-voyagers.atlassian.net/browse/P2-170?atlOrigin=eyJpIjoiNjFhZGJkMmQ4MGExNDk5ZWJiZTQ0MDE5NTc1ZTQ2MTciLCJwIjoiaiJ9
=> feat: delete picker

src/api/axios.ts, src/components/pickers/PickerDrawer.tsx, src/hooks/useQueryCache.ts, src/layouts/BasicHome.tsx, src/layouts/MainLayout.tsx, src/pages/Pickers/Pickers.tsx, src/theme.tsx
Ticket:
https://team-voyagers.atlassian.net/browse/P2-171?atlOrigin=eyJpIjoiNDJlOTBiZDI3ZTA2NGNlMzkyNzUwZGUxODk5NDU5OWEiLCJwIjoiaiJ9
=> P2 171 fe picker detail

src/api/endpoints.ts, src/api/login.ts, src/pages/App/App.tsx, src/pages/Login/Login.tsx, src/shared/paths.ts
https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?assignee=712020%3Aa4d78f0d-920a-427a-a5ce-b36979797950&selectedIssue=P2-164
=> P2 164 login

.eslintrc.cjs, .github/workflows/lang.yml, README.md, compiled-lang/en.json, compiled-lang/es.json, lang/en.json, lang/es.json, package.json, src/components/pickers/CreatePicker.tsx, src/components/pickers/PickerDrawer.tsx, src/components/pickers/UpdatePicker.tsx, src/context/LocaleProvider.tsx, src/hooks/usePersistedState.ts, src/layouts/BasicHome.tsx, src/layouts/MainLayout.tsx, src/main.tsx, src/pages/Pickers/Pickers.tsx
Ticket:
https://team-voyagers.atlassian.net/browse/P2-199?atlOrigin=eyJpIjoiNTg2YThmNTZjM2NmNDkzNmI4YzY0MzFkNjI4OTBlZDAiLCJwIjoiaiJ9
Internationalization with react-intl:
https://formatjs.io/docs/react-intl/api
=> P2 199 fe internationalization

src/pages/HarvestLogs/HarvestLogs.tsx
ticket: https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?assignee=712020%3Afab2d613-629c-4766-961f-4fc575d34b06&selectedIssue=P2-186
=> P2 186 fe harvest log list filters

src/components/harvestLogs/HarvestLogDrawer.tsx, src/components/pickers/PickerDrawer.tsx, src/context/AlertProvider.tsx
Ticket: https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?assignee=712020%3Afab2d613-629c-4766-961f-4fc575d34b06&selectedIssue=P2-208
States added for "success" | "error" | "warning" | "info"
=> P2 208 fe snackbar

package.json, src/api/axios.ts, src/api/login.ts, src/context/UserProvider.tsx, src/layouts/MainLayout.tsx, src/pages/App/App.tsx, src/pages/HarvestLogs/HarvestLogs.tsx, src/pages/Login/Login.tsx, src/pages/Payroll/Payroll.tsx, src/pages/Pickers/Pickers.tsx, src/pages/Seasons/Seasons.tsx, src/shared/ajv.ts, src/theme.tsx, yarn.lock
Ticket:
https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?selectedIssue=P2-235
- Login schema added
- Login form refactored
- UserProvider added
- Axios interceptor with headers added
=> P2 235 fe user provider

.eslintrc.cjs, package.json, src/components/SearchDataGrid.tsx, src/components/SortDataGrid.tsx, src/pages/Pickers/Pickers.tsx, yarn.lock
Ticket:
https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?assignee=712020%3A348feb69-2c99-496b-aa7a-46d4f401b598&selectedIssue=P2-173
Create Sort selector and Seach
=> feat: create sort and search generic components

compiled-lang/en.json, lang/en.json, src/components/harvestLogs/CreateHarvestLog.tsx, src/components/pickers/CreatePicker.tsx, src/layouts/MainLayout.tsx, src/pages/Payroll/Payroll.tsx, src/pages/Seasons/Seasons.tsx
ticket: https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?selectedIssue=P2-212
=> P2 212 fe icons

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
Removed the Reproduction URL input
=> Bug report form update

package.json, src/api/deductions.ts, src/api/endpoints.ts, src/api/seasons.ts, src/components/SearchDataGrid.tsx, src/components/seasons/SeasonDeductions.tsx, src/components/seasons/SeasonDrawer.tsx, src/components/seasons/SelectFreeSolo.tsx, src/theme.tsx, yarn.lock
Ticket:
https://team-voyagers.atlassian.net/browse/P2-262?atlOrigin=eyJpIjoiYzY2MjE5OWU1MzI4NGMwYWE4ZjFjMDMxMjM0NzAxZDUiLCJwIjoiaiJ9
=> feat: add deductions to season

src/pages/HarvestLogs/HarvestLogs.tsx
ticket: https://team-voyagers.atlassian.net/browse/P2-284?atlOrigin=eyJpIjoiMTA4ZGUxMDhhOTczNGE3ZDljMWJjZmUxODI1YTYzZmEiLCJwIjoiaiJ9
=> P2 284 fe harvest log date filters and quick search

src/layouts/BasicHome.tsx, src/theme.tsx
Ticket:
https://team-voyagers.atlassian.net/browse/P2-217?atlOrigin=eyJpIjoiMTk2NGYxMDg2NGYzNDUzYTk3ZWQ1OTc5MWEwYWQ2YjUiLCJwIjoiaiJ9
=> 2. feat: breadcrumb style changes

src/api/deductions.ts, src/api/products.ts, src/components/seasons/CreateSeason.tsx, src/components/seasons/SeasonDeductions.tsx, src/components/seasons/SeasonDrawer.tsx, src/components/seasons/SelectFreeSolo.tsx
[JIRA FE - Season - Create Product](https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?assignee=712020%3Aa4d78f0d-920a-427a-a5ce-b36979797950&selectedIssue=P2-259)
=> feat: fresolo product

src/components/harvestLogs/HarvestLogDrawer.tsx, src/components/seasons/SeasonDrawer.tsx, src/layouts/MainLayout.tsx, src/pages/Pickers/Pickers.tsx, src/theme.tsx
Tickets:
https://team-voyagers.atlassian.net/browse/P2-214?atlOrigin=eyJpIjoiZWM3NDdiYzlhYTFhNDU3ZTkzZjA5NzlmYjZhMjg1MzIiLCJwIjoiaiJ9
https://team-voyagers.atlassian.net/browse/P2-216?atlOrigin=eyJpIjoiYWY1MTRlNDJlMmU3NDM0Mzg1YjhiYTdmNDMzNWJjYzUiLCJwIjoiaiJ9
=> feat: input styles

src/components/SearchDataGrid.tsx, src/layouts/BasicHome.tsx, src/theme.tsx, src/ui/DataTable.tsx
Ticket:
https://team-voyagers.atlassian.net/browse/P2-216?atlOrigin=eyJpIjoiYWY1MTRlNDJlMmU3NDM0Mzg1YjhiYTdmNDMzNWJjYzUiLCJwIjoiaiJ9
=> style: Pickers dashboard

src/components/harvestLogs/FiltersDrawer.tsx, src/pages/HarvestLogs/HarvestLogs.tsx, src/theme.tsx
Ticket:
https://team-voyagers.atlassian.net/browse/P2-288?atlOrigin=eyJpIjoiMDk5MWI5NDE2N2FlNDIwOTgxZGU0ZWU1NTQ5MjcyMmYiLCJwIjoiaiJ9
=> style: harvest log dashboard

compiled-lang/en.json, lang/en.json, src/components/harvestLogs/HarvestLogDrawer.tsx, src/components/pickers/PickerDrawer.tsx, src/components/seasons/SeasonDeductions.tsx, src/components/seasons/SeasonDrawer.tsx, src/layouts/MainLayout.tsx, src/ui/ConfirmationDrawer.tsx, src/ui/DrawerContainer.tsx, src/ui/InputLabel.tsx
Tickets:
https://team-voyagers.atlassian.net/browse/P2-286
https://team-voyagers.atlassian.net/browse/P2-289
https://team-voyagers.atlassian.net/browse/P2-294
=> feat: drawer form style

src/components/harvestLogs/HarvestLogDrawer.tsx, src/components/pickers/PickerDrawer.tsx, src/components/seasons/SeasonDrawer.tsx, src/pages/HarvestLogs/HarvestLogs.tsx, src/ui/Detail.tsx, src/ui/DrawerContainer.tsx, src/ui/InputLabel.tsx, src/ui/Tag.tsx
Ticket:
https://team-voyagers.atlassian.net/browse/P2-290
https://team-voyagers.atlassian.net/browse/P2-295
=> feat: harvest log and season details

src/api/units.ts, src/components/seasons/SeasonDrawer.tsx, yarn.lock
[JIRA](https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?assignee=712020%3Aa4d78f0d-920a-427a-a5ce-b36979797950&selectedIssue=P2-260)
=> feat: Create Unit

compiled-lang/en.json, compiled-lang/es.json, lang/en.json, lang/es.json, package-lock.json, src/components/dashboard/DashboardLayout.tsx, src/components/dashboard/SplineGraph.tsx, src/components/harvestLogs/CreateHarvestLog.tsx, src/components/payroll/PayrollConfirmationModal.tsx, src/components/seasons/SeasonDeductions.tsx, src/components/seasons/SeasonDrawer.tsx, src/pages/HarvestLogs/HarvestLogs.tsx, src/pages/Payroll/Payroll.tsx, src/pages/Pickers/Pickers.tsx, src/pages/Preview/Preview.tsx, src/pages/Seasons/Seasons.tsx, src/shared/date-helpers.ts, yarn.lock
[JIRA](https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?assignee=712020%3Aa4d78f0d-920a-427a-a5ce-b36979797950&selectedIssue=P2-337)
=> fix: some large text in spanish

src/pages/Preview/Preview.tsx, src/pages/Seasons/Seasons.tsx
=> fix: farm name breadcrumb

src/pages/Login/Login.tsx
=> fix: Login - Login card bottom alignment

compiled-lang/en.json, compiled-lang/es.json, lang/en.json, lang/es.json, src/components/dashboard/DashboardLayout.tsx, src/pages/Seasons/Seasons.tsx
=> 165 bug seasons closed seasons should not have the star in the table row

src/components/harvestLogs/HarvestLogDrawer.tsx, src/pages/HarvestLogs/HarvestLogs.tsx
=> feat: invalidate harvest log query to trigger a refetch

src/components/dashboard/SplineGraph.tsx
=> fix: Dashboard - Wrong size and colors for time range tabs
